FROM openjdk:18.0.2-jdk

ARG ARG_USE_TRACES
ENV USE_TRACES=${ARG_USE_TRACES}

COPY build/libs/gripcloud-admin-0.0.1-SNAPSHOT.jar /home/grip/deploy/gripcloud-admin.jar
COPY scripts/prod /home/grip/scripts

#ADD otel-agent/aws-opentelemetry-agent.jar /opt/aws-opentelemetry-agent.jar

EXPOSE 8070
ENTRYPOINT ["/home/grip/scripts/startup.sh", "gripcloud-admin.jar"]
