FROM openjdk:18.0.2-jdk

ARG ARG_USE_TRACES
ENV USE_TRACES=${ARG_USE_TRACES}

COPY build/libs/my-kopring-0.0.1-SNAPSHOT.jar /home/grip/deploy/my-kopring.jar
COPY scripts/dev /home/grip/scripts

#ADD otel-agent/aws-opentelemetry-agent.jar /opt/aws-opentelemetry-agent.jar

EXPOSE 8070
ENTRYPOINT ["/home/grip/scripts/startup.sh", "my-kopring.jar"]
